### ISSUE TITLE
CRD Chart Improvements

### ISSUE THREAD

**Issue by aiyengar2** [rancher/charts-build-scripts#1]
Add a set of additional flags that can modify the templates/ directory of a CRD chart on prepare:

```yaml
# Under additionalCharts[i].crdOptions
prepareOptions:
  syncVersionWithMainChart: # whether to automatically update the version on the templates/Chart.yaml to match the main chart's version        
```
