### ISSUE TITLE
Support the ability to fork manifests into specific locations of a chart

### ISSUE THREAD

**Issue by aiyengar2** [rancher/charts-build-scripts#8]
Add the following field to Charts and AdditionalCharts to support forking manifests

```yaml
manifests:
- url: <required> # UpstreamOptions
  subdirectory: <optional> # UpstreamOptions
  commit: <optional> # UpstreamOptions
  filepath: <optional> # a specific file in the subdirectory to pull in the manifest for
  manifestPath: <required> # Where to drop the manifests, directories along path will be created if they don't exist
```
